version: '3.8'

services:
  claude-ide:
    build:
      context: .
      dockerfile: Dockerfile.claude-ide
    container_name: claude-ide
    environment:
      - DEFAULT_WORKSPACE=/workspace
      - PASSWORD=
      - AUTH=none
    command: [
      "--bind-addr", "0.0.0.0:8080",
      "--auth", "none",
      "--disable-telemetry",
      "/workspace"
    ]
    volumes:
      - ./workspace:/workspace
      - ./config:/config
    ports:
      - "8082:8080"  # VS Code web interface
      - "3001:3000"  # Optional: for web apps
    restart: unless-stopped
    security_opt:
      - no-new-privileges=false
    cap_add:
      - SETUID
      - SETGID
    tmpfs:
      - /tmp
      - /run
      - /var/run
      - /home/coder/.config
    user: root

  # Add MCP server configuration if needed
  # mcp-server:
  #   image: your-mcp-server-image
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - MCP_CONFIG=...
  #   volumes:
  #     - ./mcp-config:/etc/mcp
