version: '3.8'

services:
  # Claude Code (Node.js CLI)
  claude-code:
    image: node:18-bookworm
    container_name: claude-code
    user: root  # Run as root to avoid permission issues
    environment:
      - NODE_ENV=development
      - HOME=/home/node
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - NPM_CONFIG_PREFIX=/home/node/.npm-global
      - PATH=/home/node/.npm-global/bin:${PATH}
    volumes:
      - ./workspace:/workspace
      - claude-code-cache:/home/node/.npm
      - claude-code-config:/home/node/.config
    working_dir: /workspace
    stdin_open: true
    tty: true
    entrypoint: |
      /bin/sh -c '
      # Fix permissions for the node user
      chown -R node:node /home/node && \
      # Install the Claude SDK globally
      su -c "npm install -g @anthropic-ai/sdk" node && \
      # Start the container as the node user
      su -c "node" node'
    ports:
      - "3000:3000"  # For Claude Code web UI if needed
    restart: unless-stopped

  # VS Code in Browser
  vscode:
    build:
      context: .
      dockerfile: Dockerfile.claude-ide
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - TZ=${TZ:-UTC}
        - VSCODE_PASSWORD=${VSCODE_PASSWORD:-coder}
        - SUDO_PASSWORD=${SUDO_PASSWORD:-coder}
        - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
    container_name: claude-vscode
    user: root  # Run as root initially to set up permissions
    environment:
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      - TZ=${TZ:-UTC}
      - PASSWORD=${VSCODE_PASSWORD:-coder}
      - SUDO_PASSWORD=${SUDO_PASSWORD:-coder}
      - DEFAULT_WORKSPACE=/workspace
      - DOCKER_USER=coder
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - PATH=/home/coder/.local/bin:${PATH}
    volumes:
      - .:/workspace
      - vscode-extensions:/home/coder/.local/share/code-server/extensions
      - vscode-config:/home/coder/.config
      - claude-cli:/home/coder/.local/bin
    ports:
      - "8083:8080"  # Using port 8083 to avoid conflicts with other services
    working_dir: /workspace
    restart: unless-stopped
    entrypoint: |
      /bin/sh -c '
      # Fix permissions for the coder user
      chown -R coder:coder /home/coder && \
      chown -R coder:coder /workspace && \
      # Ensure config directory exists
      mkdir -p /home/coder/.config/code-server && \
      # Create local bin directory
      mkdir -p /home/coder/.local/bin && \
      # Install Claude CLI wrapper
      if [ -f /workspace/scripts/cli-wrapper.sh ]; then
        cp /workspace/scripts/cli-wrapper.sh /home/coder/.local/bin/claude && \
        chmod +x /home/coder/.local/bin/claude && \
        chown coder:coder /home/coder/.local/bin/claude && \
        echo "Installed Claude CLI wrapper to /home/coder/.local/bin/claude"
      fi && \
      # Install Anthropic SDK globally
      echo "Installing @anthropic-ai/sdk..." && \
      su -c "npm install -g @anthropic-ai/sdk" coder && \
      # Generate a random token
      export TOKEN=$(openssl rand -hex 16) && \
      # Set the token in config file
      echo "bind-addr: 0.0.0.0:8080" > /home/coder/.config/code-server/config.yaml && \
      echo "auth: none" >> /home/coder/.config/code-server/config.yaml && \
      echo "password: ${TOKEN}" >> /home/coder/.config/code-server/config.yaml && \
      echo "cert: false" >> /home/coder/.config/code-server/config.yaml && \
      # Set correct permissions
      chown -R coder:coder /home/coder/.config && \
      # Display the token for login (remove this in production)
      echo "========================================" && \
      echo "VS Code Access Token: ${TOKEN}" && \
      echo "Access at: http://localhost:8083" && \
      echo "" && \
      echo "Claude CLI is available. Type 'claude' to start." && \
      echo "========================================" && \
      # Start code-server as the coder user
      su -c "code-server --bind-addr 0.0.0.0:8080 --auth none --disable-telemetry" coder'

volumes:
  claude-code-cache:
  claude-code-config:
  vscode-extensions:
  vscode-config:
  claude-cli:
